### ISSUE TITLE
Cannot bind argument to parameter 'alertUid' because it is null

### ISSUE THREAD

**Issue by dschnardat** [lwhitelock/DattoRMM-Alert-HaloPSA#6]
I am in the process of configuring the dattoRMM-Alert-HaloPSA webhook receiver and am receiving errors indicating that the alertUID is null. I'm receiving a couple of different sets of errors that don't really make a lot of sense at this time.

I've run my JSON file through VSCODE formatting and cannot find any errors. Further, I have checked to make sure that the formatting appears correct (see below). Any help would be appreciated.

{
    "troubleshootingNote": "Please ensure that the device is turned back on",
    "docURL": "https://halo.mydomain.com/kb?id=999999999999",
    "showDeviceDetails": true,
    "showDeviceStatus": true,
    "showAlertDetails": true,
    "alertUID": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "alertMessage": "Device went Offline",
    "platform": "Zinfandel"
}

2023-06-14T20:24:52Z   [Verbose]   [HostMonitor] Checking worker statuses (Count=1)
2023-06-14T20:24:52Z   [Verbose]   [HostMonitor] Worker status: ID=dd365304-XXXX-XXXX-XXXX-XXXXXXXXXXXXXXX, Latency=52ms
2023-06-14T20:24:52Z   [Information]   Executing StatusCodeResult, setting HTTP status code 200
2023-06-14T20:41:11Z   [Verbose]   Request successfully matched the route with name 'Receive-Alert' and template 'api/Receive-Alert'
2023-06-14T20:41:11Z   [Information]   Executing 'Functions.Receive-Alert' (Reason='This function was programmatically called via the host APIs.', Id=b6db991e-54b6-45a1-b299-64b52b0d950c)
2023-06-14T20:41:11Z   [Verbose]   Sending invocation id: 'b6db991e-XXXX-XXXX-XXXX-XXXXXXXXXXXXX
2023-06-14T20:41:11Z   [Verbose]   Posting invocation id:b6db991e-54b6-XXXX-XXXX-XXXXXXXXXXXX on workerId:dd365304-a0ab-4d30-9231-f06dd0100556
2023-06-14T20:41:11Z   [Information]   INFORMATION: Processing Webhook for Alert fa7e4e27-XXXX-XXXX-XXXX-XXXXXXXXXXX
2023-06-14T20:41:11Z   [Error]   ERROR: Conversion from JSON failed with error: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.

Exception             : 
    Type           : System.ArgumentException
    Message        : Conversion from JSON failed with error: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
    TargetSite     : 
        Name          : ConvertFromJson
        DeclaringType : Microsoft.PowerShell.Commands.JsonObject
        MemberType    : Method
        Module        : Microsoft.PowerShell.Commands.Utility.dll
    InnerException : 
        Type       : Newtonsoft.Json.JsonReaderException
        TargetSite : 
            Name          : ParseValue
            DeclaringType : Newtonsoft.Json.JsonTextReader
            MemberType    : Method
            Module        : Newtonsoft.Json.dll
        Message    : Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
        Source     : Newtonsoft.Json
        HResult    : -2146233088
        StackTrace : 
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, JsonSerializerSettings settings)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable, Nullable`1 maxDepth, ErrorRecord& error)
    Source         : Microsoft.PowerShell.Commands.Utility
    HResult        : -2147024809
    StackTrace     : 
   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable, Nullable`1 maxDepth, ErrorRecord& error)
   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
InvocationInfo        : 
    MyCommand        : ConvertFrom-Json
    ScriptLineNumber : 38
    OffsetInLine     : 33
    HistoryId        : 1
    ScriptName       : C:\home\site\wwwroot\Receive-Alert\run.ps1
    Line             : $AlertWebhook = $Request.Body | convertfrom-json -depth 100
                       
    PositionMessage  : At C:\home\site\wwwroot\Receive-Alert\run.ps1:38 char:33
                       + $AlertWebhook = $Request.Body | convertfrom-json -depth 100
                       +                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\home\site\wwwroot\Receive-Alert
    PSCommandPath    : C:\home\site\wwwroot\Receive-Alert\run.ps1
    InvocationName   : convertfrom-json
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\Receive-Alert\run.ps1: line 38

--------------------------------------------------------------------------------------------------------------

In addition, I receive the following errors

--------------------------------------------------------------------------------------------------------------

2023-06-14T20:41:12Z   [Verbose]   PROGRESS: Reading response stream... (Number of bytes read: 0)
2023-06-14T20:41:12Z   [Verbose]   PROGRESS: Reading response stream... (Number of bytes read: 782)
2023-06-14T20:41:12Z   [Verbose]   PROGRESS: Reading web response completed. (Number of bytes read: 782)
2023-06-14T20:41:12Z   [Error]   ERROR: Cannot bind argument to parameter 'alertUid' because it is null.

Exception             : 
    Type              : System.Management.Automation.ParameterBindingValidationException
    Message           : Cannot bind argument to parameter 'alertUid' because it is null.
    ParameterName     : alertUid
    ParameterType     : System.Object
    ErrorId           : ParameterArgumentValidationErrorNullNotAllowed
    Line              : 348
    Offset            : 38
    CommandInvocation : 
        MyCommand        : Get-DrmmAlert
        ScriptLineNumber : 348
        OffsetInLine     : 14
        HistoryId        : 1
        ScriptName       : C:\home\site\wwwroot\Modules\CoreHelper.psm1
        Line             : $Alert = Get-DrmmAlert -alertUid $AlertID
                           
        PositionMessage  : At C:\home\site\wwwroot\Modules\CoreHelper.psm1:348 char:14
                           +     $Alert = Get-DrmmAlert -alertUid $AlertID
                           +              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PSScriptRoot     : C:\home\site\wwwroot\Modules
        PSCommandPath    : C:\home\site\wwwroot\Modules\CoreHelper.psm1
        InvocationName   : Get-DrmmAlert
        PipelineLength   : 1
        PipelinePosition : 1
        CommandOrigin    : Internal
    ErrorRecord       : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot bind argument to parameter 'alertUid' because it is null.
            HResult : -2146233087
        CategoryInfo          : InvalidData: (:) [Get-DrmmAlert], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-DrmmAlert
        InvocationInfo        : 
            MyCommand        : Get-DrmmAlert
            ScriptLineNumber : 348
            OffsetInLine     : 38
            HistoryId        : 1
            ScriptName       : C:\home\site\wwwroot\Modules\CoreHelper.psm1
            Line             : $Alert = Get-DrmmAlert -alertUid $AlertID
                               
            PositionMessage  : At C:\home\site\wwwroot\Modules\CoreHelper.psm1:348 char:38
                               +     $Alert = Get-DrmmAlert -alertUid $AlertID
                               +                                      ~~~~~~~~
            PSScriptRoot     : C:\home\site\wwwroot\Modules
            PSCommandPath    : C:\home\site\wwwroot\Modules\CoreHelper.psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Get-AlertEmailBody, C:\home\site\wwwroot\Modules\CoreHelper.psm1: line 348
                                at <ScriptBlock>, C:\home\site\wwwroot\Receive-Alert\run.ps1: line 41
    TargetSite        : 
        Name          : ValidateNullOrEmptyArgument
        DeclaringType : System.Management.Automation.ParameterBinderBase, System.Management.Automation, Version=7.2.10.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        : 
   at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type argumentType, Object parameterValue, Boolean recurseIntoCollections)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
   at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidData: (:) [Get-DrmmAlert], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-DrmmAlert
InvocationInfo        : 
    MyCommand        : Get-DrmmAlert
    ScriptLineNumber : 348
    OffsetInLine     : 38
    HistoryId        : 1
    ScriptName       : C:\home\site\wwwroot\Modules\CoreHelper.psm1
    Line             : $Alert = Get-DrmmAlert -alertUid $AlertID
                       
    PositionMessage  : At C:\home\site\wwwroot\Modules\CoreHelper.psm1:348 char:38
                       +     $Alert = Get-DrmmAlert -alertUid $AlertID
                       +                                      ~~~~~~~~
    PSScriptRoot     : C:\home\site\wwwroot\Modules
    PSCommandPath    : C:\home\site\wwwroot\Modules\CoreHelper.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at Get-AlertEmailBody, C:\home\site\wwwroot\Modules\CoreHelper.psm1: line 348
                        at <ScriptBlock>, C:\home\site\wwwroot\Receive-Alert\run.ps1: line 41

**Comment by stabilitynetworks** [comment]
I have this issue as well
